apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo
  namespace: demo-namespace   # Avoid default namespace (CKV_K8S_21)
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      automountServiceAccountToken: false   # CKV_K8S_38
      securityContext:                      # Pod-level security context (CKV_K8S_29)
        runAsNonRoot: true
        runAsUser: 10001                     # CKV_K8S_40
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: demo
          image: ghcr.io/adi-czobel/demo@sha256:6cb355201227459ffb4ce564e12f90d185d42ec5c9d40f227c8bf863a14663c3
          imagePullPolicy: Always           # CKV_K8S_15
          securityContext:                  # Container-level security context (CKV_K8S_30)
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001                 # CKV_K8S_40
            capabilities:
              drop:
                - ALL                       # CKV_K8S_37, CKV_K8S_28
          resources:                        # CKV_K8S_10, CKV_K8S_11, CKV_K8S_12, CKV_K8S_13
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          ports:
            - containerPort: 80
          readinessProbe:                   # CKV_K8S_9
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:                    # CKV_K8S_8
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy                      # CKV2_K8S_6
metadata:
  name: demo-network-policy
  namespace: demo-namespace
spec:
  podSelector:
    matchLabels:
      app: demo
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - podSelector: {}
