name: Dependabot Badge

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  security-events: read

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare badges branch
        run: |
          git init .
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch origin badges || true
          if git rev-parse --verify origin/badges >/dev/null 2>&1; then
            git checkout badges
            git reset --hard origin/badges
          else
            git checkout --orphan badges
            rm -rf *
          fi

      - name: Get Dependabot alert count
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set +e
          OUT=$(gh api -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/dependabot/alerts -q 'length(.)' 2>err)
          RC=$?
          set -e

          if [ $RC -ne 0 ] && grep -qi "Dependabot alerts are disabled" err; then
            MSG="disabled"
            COLOR=lightgrey
            COUNT=0
          elif [ $RC -ne 0 ]; then
            MSG="unknown"
            COLOR=lightgrey
            COUNT=0
          else
            COUNT=${OUT:-0}
            MSG="$COUNT open"
            COLOR=brightgreen
            if [ "$COUNT" -gt 0 ]; then COLOR=orange; fi
            if [ "$COUNT" -gt 10 ]; then COLOR=red; fi
          fi

          curl -s "https://img.shields.io/badge/dependabot-$MSG-$COLOR" > dependabot-badge.svg

      - name: Commit and push badge
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: actions@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: actions@users.noreply.github.com
        run: |
          git add dependabot-badge.svg
          git commit -m "Update Dependabot badge" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:badges
