name: Update Badges

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 * * * *" # hourly
  workflow_dispatch:

permissions:
  contents: write
  security-events: read

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare badges branch
        run: |
          git init .
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch origin badges || true
          if git rev-parse --verify origin/badges >/dev/null 2>&1; then
            git checkout badges
            git reset --hard origin/badges
          else
            git checkout --orphan badges
            rm -rf *
          fi

      # CI Badge
      - name: Generate CI badge
        run: |
          curl -s "https://img.shields.io/github/actions/workflow/status/${{ github.repository }}/ci.yml?label=CI&logo=github" > ci-badge.svg

      # Policy Checks Badge
      - name: Generate Policy Checks badge
        run: |
          curl -s "https://img.shields.io/github/actions/workflow/status/${{ github.repository }}/policy.yml?label=Policy%20Checks&logo=github" > policy-badge.svg

      # Release Badge
      - name: Generate Release badge
        run: |
          curl -s "https://img.shields.io/github/actions/workflow/status/${{ github.repository }}/release.yml?label=Release&logo=github" > release-badge.svg

      # Security Checks Badge
      - name: Generate Security Checks badge
        run: |
          curl -s "https://img.shields.io/github/actions/workflow/status/${{ github.repository }}/security.yml?label=Security%20Checks&logo=github" > security-badge.svg

      # Dependabot Badge (with safe skip)
      - name: Get Dependabot alert count
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set +e
          OUT=$(gh api -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/dependabot/alerts -q 'length(.)' 2>err)
          RC=$?
          set -e

          if [ $RC -ne 0 ] && grep -qi "Dependabot alerts are disabled" err; then
            MSG="disabled"
            COLOR=lightgrey
          elif [ $RC -ne 0 ]; then
            MSG="unknown"
            COLOR=lightgrey
          else
            COUNT=${OUT:-0}
            MSG="$COUNT open"
            COLOR=brightgreen
            if [ "$COUNT" -gt 0 ]; then COLOR=orange; fi
            if [ "$COUNT" -gt 10 ]; then COLOR=red; fi
          fi

          curl -s "https://img.shields.io/badge/dependabot-$MSG-$COLOR" > dependabot-badge.svg

      - name: Commit and push all badges
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: actions@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: actions@users.noreply.github.com
        run: |
          git add *.svg
          git commit -m "Update workflow badges" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:badges
